server:
  port: 8764
spring:
  application:
    name: fastDFSZuul
#  main:
#    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#management:
#  security:
#    enabled: false
zuul:
  routes:
    api-a:
      path: /upload
      serviceId: fastDFSProducer
#zuul:
#  routes:
#    baidu:
#      path: /it/**
#      url: http://www.ityouknow.com/
