server:
  port: 8762
spring:
  application:
    name: fastDFSConsumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

#management:
#  security:
#    enabled: false
